In [1]:
import torch

x = torch.tensor([[1, 2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [4]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [5]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.randint(low=0, high=10, size=(3, 4))

tensor([[7, 5, 0, 4],
        [2, 6, 7, 2],
        [9, 7, 9, 9]])

In [8]:
torch.rand((3, 4))

tensor([[0.3453, 0.0502, 0.4434, 0.2486],
        [0.0776, 0.9017, 0.0497, 0.9440],
        [0.6371, 0.5470, 0.0457, 0.2360]])

In [9]:
torch.randn((3, 4))

tensor([[ 2.1751,  0.5603, -0.5460, -2.4160],
        [ 1.8996,  0.8661,  1.1647,  0.4197],
        [ 0.1042, -1.0501, -0.9008,  1.5428]])

In [10]:
import numpy as np

x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
print(type(x), type(y))
# <class 'numpy.ndarray'> <class 'torch.Tensor'>

<class 'numpy.ndarray'> <class 'torch.Tensor'>
